### ISSUE TITLE
ReferenceError: n is not defined

### ISSUE THREAD

**Issue by ethancfchen** [exif-js/exif-js#120]
At function `getStringFromDB`, line 741: 
```javascript
for (n = start; n < start + length; n++) {
    outstr += String.fromCharCode(buffer.getUint8(n));
}
```
the variable `n` is not defined.

**Comment by mmase** [comment]
Anyone have any ideas?

**Comment by mmase** [comment]
I just literally added `var` in front of `n`. There is something about the context of this shorthand that makes it complain.

**Comment by bartvanderwal** [comment]
@mmase This happens when you use [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode). It's been there since JS v5 (2009, thanks to Douglas Crockford :)). In strict mode you can not tnot declare a new variable without an explicit `var`. Probably some other bit of JavaScript has a `"use strict";` in it, and then you use exif.

Plenty of other people have complained about this. But there are some other `for` loops that also don't have `var` yet. But I'll check the pull request.

**Comment by Cayan** [comment]
I'm still facing this issue today, is there any update or plans to fix this?

**Comment by matteobucci** [comment]
> I'm still facing this issue today, is there any update or plans to fix this?

Is it possible that you are still using version 2.3.0? I'm facing the same issue and I'm going to fork this repository and use mine as dependency

**Comment by MikeKovarik** [comment]
@Cayan @matteobucci  Hello guys. I would recommend using [exifr](https://github.com/MikeKovarik/exifr). An alternative and faster library with more features that i started developing since exif-js is no longer maintained.

**Comment by LuckyArdhika** [comment]
this issue lives for 3 years

**Comment by raju-mechatronics** [comment]
issue lives on...

**Comment by rdonadeu** [comment]
After hours of trying to make this library work. It was as easy as installing exifr

> @Cayan @matteobucci Hello guys. I would recommend using [exifr](https://github.com/MikeKovarik/exifr). An alternative and faster library with more features that i started developing since exif-js is no longer maintained.
